[2021-06-08 09:30:44] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:30:52] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 Command line code(1): include_once()
#1 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 Command line code(1): include_once()
#1 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:30:56] local.ERROR: Uncaught TypeError: Illuminate\Translation\FileLoader::loadNamespaceOverrides(): Argument #1 ($lines) must be of type array, int given, called in D:\xampp\htdocs\foodtiger\vendor\laravel\framework\src\Illuminate\Translation\FileLoader.php on line 86 and defined in D:\xampp\htdocs\foodtiger\vendor\laravel\framework\src\Illuminate\Translation\FileLoader.php:101
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\laravel\framework\src\Illuminate\Translation\FileLoader.php(86): Illuminate\Translation\FileLoader->loadNamespaceOverrides(1, 'en', 'mailable', 'maileclipse')
#1 D:\xampp\htdocs\foodtiger\vendor\laravel\framework\src\Illuminate\Translation\FileLoader.php(70): Illuminate\Translation\FileLoader->loadNamespaced('en', 'mailable', 'maileclipse')
#2 D:\xampp\htdocs\foodtiger\vendor\laravel\framework\src\Illuminate\Translation\Translator.php(279): Illuminate\Translation\FileLoader->load('en', 'mailable', 'maileclipse')
#3 D:\xampp\htdocs\foodtiger\vendor\laravel\framework\src\Illuminate\Translation\Translator.php(191): Illuminate\Translation\Translator->load('maileclipse', 'mailable', 'en')
#4 D:\xampp\htdocs\foodtiger\vendor\laravel\framework\src\Illuminate\Translation\Translator.php(126): Illuminate\Translation\Translator->getLine('maileclipse', 'mailable', 'en', NULL, Array)
#5 D:\xampp\htdocs\foodtiger\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(804): Illuminate\Translation\Translator->get('maileclipse::ma...', Array, 'en')
#6 D:\xampp\htdocs\foodtiger\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(839): trans('maileclipse::ma...', Array, NULL)
#7 Command line code(1): __('maileclipse::ma...')
#8 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught TypeError: Illuminate\\Translation\\FileLoader::loadNamespaceOverrides(): Argument #1 ($lines) must be of type array, int given, called in D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php on line 86 and defined in D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php:101
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php(86): Illuminate\\Translation\\FileLoader->loadNamespaceOverrides(1, 'en', 'mailable', 'maileclipse')
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php(70): Illuminate\\Translation\\FileLoader->loadNamespaced('en', 'mailable', 'maileclipse')
#2 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(279): Illuminate\\Translation\\FileLoader->load('en', 'mailable', 'maileclipse')
#3 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(191): Illuminate\\Translation\\Translator->load('maileclipse', 'mailable', 'en')
#4 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(126): Illuminate\\Translation\\Translator->getLine('maileclipse', 'mailable', 'en', NULL, Array)
#5 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(804): Illuminate\\Translation\\Translator->get('maileclipse::ma...', Array, 'en')
#6 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(839): trans('maileclipse::ma...', Array, NULL)
#7 Command line code(1): __('maileclipse::ma...')
#8 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php:101)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:31:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:32:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:33:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:34:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:35:39] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:36:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:37:39] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:38:39] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:39:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:40:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:41:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:42:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:43:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:44:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:45:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:46:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:47:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:48:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:49:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:50:35] local.ERROR: Geocoding failed because `You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account` {"userId":2,"exception":"[object] (Spatie\\Geocoder\\Exceptions\\CouldNotGeocode(code: 0): Geocoding failed because `You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account` at D:\\xampp\\htdocs\\foodtiger\\vendor\\spatie\\geocoder\\src\\Exceptions\\CouldNotGeocode.php:16)
[stacktrace]
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\spatie\\geocoder\\src\\Geocoder.php(96): Spatie\\Geocoder\\Exceptions\\CouldNotGeocode::serviceReturnedError('You must use an...')
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\spatie\\geocoder\\src\\Geocoder.php(75): Spatie\\Geocoder\\Geocoder->getAllCoordinatesForAddress('bufflo')
#2 D:\\xampp\\htdocs\\foodtiger\\app\\Http\\Controllers\\FrontEndController.php(393): Spatie\\Geocoder\\Geocoder->getCoordinatesForAddress('bufflo')
#3 D:\\xampp\\htdocs\\foodtiger\\app\\Http\\Controllers\\FrontEndController.php(146): App\\Http\\Controllers\\FrontEndController->showStores(NULL)
#4 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\FrontEndController->index()
#5 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#6 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\FrontEndController), 'index')
#7 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
#8 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(692): Illuminate\\Routing\\Route->run()
#9 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 D:\\xampp\\htdocs\\foodtiger\\app\\Http\\Middleware\\Language.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\Language->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#20 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 D:\\xampp\\htdocs\\foodtiger\\vendor\\mobidonia\\laravel-dashboard-installer\\src\\Middleware\\ToInstallMiddleware.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): dacoto\\LaravelInstaller\\Middleware\\ToInstallMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(694): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#30 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#31 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#32 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#33 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#34 D:\\xampp\\htdocs\\foodtiger\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 D:\\xampp\\htdocs\\foodtiger\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 D:\\xampp\\htdocs\\foodtiger\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 D:\\xampp\\htdocs\\foodtiger\\vendor\\sentry\\sentry-laravel\\src\\Sentry\\Laravel\\Tracing\\Middleware.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Sentry\\Laravel\\Tracing\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 D:\\xampp\\htdocs\\foodtiger\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 D:\\xampp\\htdocs\\foodtiger\\server.php(21): require_once('D:\\\\xampp\\\\htdocs...')
#55 {main}
"} 
[2021-06-08 09:50:38] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:50:52] local.ERROR: Geocoding failed because `You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account` {"userId":2,"exception":"[object] (Spatie\\Geocoder\\Exceptions\\CouldNotGeocode(code: 0): Geocoding failed because `You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account` at D:\\xampp\\htdocs\\foodtiger\\vendor\\spatie\\geocoder\\src\\Exceptions\\CouldNotGeocode.php:16)
[stacktrace]
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\spatie\\geocoder\\src\\Geocoder.php(124): Spatie\\Geocoder\\Exceptions\\CouldNotGeocode::serviceReturnedError('You must use an...')
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\spatie\\geocoder\\src\\Geocoder.php(108): Spatie\\Geocoder\\Geocoder->getAllAddressesForCoordinates(31.479624, 74.3000763)
#2 D:\\xampp\\htdocs\\foodtiger\\app\\Http\\Controllers\\FrontEndController.php(644): Spatie\\Geocoder\\Geocoder->getAddressForCoordinates(31.479624, 74.3000763)
#3 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\FrontEndController->getCurrentLocation(Object(Illuminate\\Http\\Request))
#4 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('getCurrentLocat...', Array)
#5 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\FrontEndController), 'getCurrentLocat...')
#6 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
#7 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(692): Illuminate\\Routing\\Route->run()
#8 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 D:\\xampp\\htdocs\\foodtiger\\app\\Http\\Middleware\\Language.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\Language->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#19 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 D:\\xampp\\htdocs\\foodtiger\\vendor\\mobidonia\\laravel-dashboard-installer\\src\\Middleware\\ToInstallMiddleware.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): dacoto\\LaravelInstaller\\Middleware\\ToInstallMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(694): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#29 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#30 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#31 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#32 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#33 D:\\xampp\\htdocs\\foodtiger\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 D:\\xampp\\htdocs\\foodtiger\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 D:\\xampp\\htdocs\\foodtiger\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 D:\\xampp\\htdocs\\foodtiger\\vendor\\sentry\\sentry-laravel\\src\\Sentry\\Laravel\\Tracing\\Middleware.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Sentry\\Laravel\\Tracing\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#51 D:\\xampp\\htdocs\\foodtiger\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#52 D:\\xampp\\htdocs\\foodtiger\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#53 D:\\xampp\\htdocs\\foodtiger\\server.php(21): require_once('D:\\\\xampp\\\\htdocs...')
#54 {main}
"} 
[2021-06-08 09:51:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:52:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:53:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:54:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:55:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:56:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:57:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:58:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 09:59:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:00:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:01:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:02:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:03:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:04:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:05:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:06:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:07:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:08:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:09:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:10:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:11:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:12:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:13:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:14:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:15:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:16:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:17:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:18:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:19:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:20:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:21:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:22:37] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:23:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:24:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:25:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-06-08 10:26:36] local.ERROR: Uncaught Error: Class "Auth0\Login\Auth0User" not found in D:\xampp\htdocs\foodtiger\app\Models\MyAuth0User.php:8
Stack trace:
#0 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(444): include()
#1 D:\xampp\htdocs\foodtiger\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 Command line code(1): class_exists('App\\Models\\MyAu...')
#4 [internal function]: {closure}('App\\Models\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Auth0\\Login\\Auth0User\" not found in D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(444): include()
#1 D:\\xampp\\htdocs\\foodtiger\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('D:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#4 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#5 Command line code(1): array_filter(Array, Object(Closure))
#6 {main}
  thrown at D:\\xampp\\htdocs\\foodtiger\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
